### ISSUE TITLE
Neighborhood GRG

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/solutions-grg-widget#1]
Discussing the GRG Widget w/ Larry Strasser, he mentioned that he's seen/used "non-standard" GRGs that were built from "organic" shapefiles, creating a reference grid from breaks in neighborhoods, lines of communication, water features, etc. With the advent of vector basemaps and the datasets that drive them, we could create a tool that develops an "NRG" for the same uses cases as the GRG.

**Comment by topowright** [comment]
Breaking this issue into smaller issues: 

https://github.com/Esri/solutions-grg-widget/issues/126

**Comment by BobBooth** [comment]
@lfunkhouser  & @topowright 
Additional related issue:
Create a GRG that takes input breaklines into account (https://github.com/Esri/solutions-grg-widget/issues/127).

**Comment by topowright** [comment]
With this issue now being captured in the following issues I think we can close this issue: 
Create a GRG within a boundary honoring existing zones within the higher boundary
#126 
Create a GRG that takes input breaklines into account
https://github.com/Esri/solutions-grg-widget/issues/127
