### ISSUE TITLE
Define by reference system (area and point) widget tools do not check if input area falls into polar region

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-grg-widget#117]
### Bug or Enhancement
The define by reference system both area and point tools do not check if the input area is located in the MGRS polar regions (i.e. north of 84N degrees; south of 80S degrees). When the user clicks "Create GRG", no error message is displayed to inform the user why the output GRG was created.

### Repo Steps or Enhancement details
I would expect the widget tools to check if the input is in or crosses into the MGRS polar regions and display an error informing that the input area is invalid. With the current behavior, users won't understand the reason why the GRG was not created.

@nfeuerstein @lfunkhouser @joebayles I've labeled this with "sprint backlog" so we can address this through documentation as a "Known Issue" and add the check and error message at another release. Thoughts?

**Comment by joebayles** [comment]
Documented

**Comment by adgiles** [comment]
Addressed in PR https://github.com/Esri/solutions-grg-widget/pull/130.

@topowright @ACueva @dfoll 

Kevin has merged the request so good for QA

**Comment by ACueva** [comment]
Checklist test updated, verified by @dfoll.

**Comment by ACueva** [comment]
Per PE discussion, no Doc changes needed.

**Comment by adgiles** [comment]
Found an issue with this during retro, reopening

**Comment by adgiles** [comment]
The original fix for this issue had a slight bug that was affecting the create Point GRG by Reference System. If the user tried to create a point GRG within a polar region with a Grid Size that was not Grid Zone the GRG would not be created and no warning was given.

On investigation if the grid origin point was in a polar region the mgrs.USNGtoPoint() function returns a point that has NaN values for its x and y. Added a check to exit the function with a warning message if this occurs.

Update to this issue in PR https://github.com/Esri/solutions-grg-widget/pull/139

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/34801461-b931476c-f61d-11e7-9898-66fab706d883.png)
This is what I have as a result from working in the polar region. I feel like this is verified. Please advise if this is not what we would expect.

**Comment by ACueva** [comment]
Sorry, was also verifying this issue.  Had some machine issues so wasn't able to assign it to myself.  I can also confirm this fix, tested against yesterday's build and then again after the changes @adgiles made. 
![2018-01-10_15-54-25](https://user-images.githubusercontent.com/3093940/34802176-02f160e6-f621-11e7-8ee8-df73aa675eef.png)
