### ISSUE TITLE
Change default toggle switch value to be true in Point using Time and Speed section

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-grg-widget#133]
### Bug or Enhancement
When first loading GRG from Point using Time and Speed, the "Define number of rows and columns" is set off.

Please change the default value to be "true" or "green" as outlined in screenshot below.
### Screenshots
![2018-01-08_14-19-09](https://user-images.githubusercontent.com/3093940/34695258-019cfbae-f47f-11e7-9374-1fc391712601.png)

**Comment by dfoll** [comment]
@lfunkhouser what pipeline do you want this in? .... i estimate it will take @adgiles or @kgonzago  about half a second to complete

**Comment by lfunkhouser** [comment]
Putting in Sprint 4; however, feel free to work on it if you have availability @adgiles @kgonzago

**Comment by adgiles** [comment]
Addressed in #135 

@dfoll @ACueva @topowright ready to verify once @kgonzago has accepted the pull request

**Comment by topowright** [comment]
This issue has been fixed : 
![image](https://user-images.githubusercontent.com/5488313/34799080-3f2cf736-f613-11e7-9512-86d684d643b7.png)
Above is what I get when I load the GRG widget from default settings
