### ISSUE TITLE
Improve experience for deleting a grid cell during the publish grg workflow

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-grg-widget#134]
Current behavior only allows you to delete a grid cell if it lands outside of range ring created.

If you right click on a grid cell located outside of the range ring the widget creates, you are able to delete the cells.

### Screenshots
![2018-01-08_14-37-39](https://user-images.githubusercontent.com/3093940/34695990-d8979702-f481-11e7-99c4-b8a97dd83c09.png)
![2018-01-08_14-39-14](https://user-images.githubusercontent.com/3093940/34695992-d9a4331c-f481-11e7-87e6-f2f5d3c5e33c.png)

**Comment by adgiles** [comment]
@dfoll this was just the order the two layers were being added, I have swapped them round which resolves the issue.

Addressed in #135 

@dfoll @ACueva @topowright ready to verify once @kgonzago has accepted the pull request

**Comment by adgiles** [comment]
Looks like a bug was accidentially introduced during the JShint process, fixed in this PR https://github.com/Esri/solutions-grg-widget/pull/156

Ready to verify once PR complete
