### ISSUE TITLE
Gridded Reference Graphic widget folder should be renamed

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-grg-widget#140]
### Bug or Enhancement
In github, the folder that you use to drop in the WAB  ...\client\stemapp\widgets folder is named "GRG", this is a different naming convention than the widgets that come with WAB, suggest changing the name of the folder to "GriddedReferenceGraphic"

I experimented with doing this myself, but it's more  involved than simply changing the folder name.

### Screenshots
![image](https://user-images.githubusercontent.com/5322669/34848124-817daf80-f6d2-11e7-96c7-a676e370d82c.png)

**Comment by dfoll** [comment]
there is at least one specific area where documentation needs changed, we refer to the "GRG" folder, and this will need changed to refer to the "GriddedReferenceGraphic" folder
http://solutions.arcgis.com/defense/help/gridded-reference-graphic/get-started/set-up-the-grg-solution-in-web-appbuilder.htm
"Install the GRG widget"  - step 5

**Comment by Dbarnes1** [comment]
@joebayles I couldn't come up with a reason we left it this way, although I know we discussed it. @dfoll asked me and I thought it was intentional, but can't think of a reason why now.

**Comment by dfoll** [comment]
@adgiles I attempted to do this myself. because I changed a folder name, the changes show that I removed and replaced all the files, however the only actual changes I made I listed above. please review thoroughly.

**Comment by adgiles** [comment]
@dfoll All looks good, the thing that normally catches people out is not renaming the name property in the manifest.json. Tested the branch and it all works as expected. All merged and branch deleted.

**Comment by ACueva** [comment]
Verified these changes work in WAB-DE.
![2018-01-12_8-45-09](https://user-images.githubusercontent.com/3093940/34885512-19d30148-f775-11e7-8823-3fb91a8bd912.png)
![2018-01-12_8-41-41](https://user-images.githubusercontent.com/3093940/34885518-1c59703c-f775-11e7-8e99-18f6072026bf.png)

**Comment by ACueva** [comment]
Just an FYI,  We aren't the only Widget that has their name cut off.  Per @Jianxia this is something the WAB team is looking into for future releases.

**Comment by dfoll** [comment]
this change in folder name was documented in CMS in the location i stated above, removed G-Doc (CMS) label

**Comment by joebayles** [comment]
FYI - Naming it 'GRG' vice 'Gridded Reference Graphic'  was precisely for this reason... It showed up as "Gridded Re..." in the menu.

**Comment by topowright** [comment]
I will have to check if that is still the issue and we will have to move back to the previous name.
