### ISSUE TITLE
Define number of rows and columns toggle options are reversed

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-grg-widget#144]
Issue reported by @MikeTschudi 

### Bug or Enhancement
The Define number of rows and columns toggle positions for "on" and "off" are reversed in the UI.

### Repo Steps or Enhancement details
1. Open GRG widget
2. Select Define a Grid from an Area
3. Select By Dimension
4. Note the Define number of rows and columns toggle button.

The user slides the toggle right (red) to disable the option to input specified number of horizontal and vertical cells and slides it left (green) to enable the option to input a specified number of horizontal and vertical cells. 

### Screenshots
![image](https://user-images.githubusercontent.com/3800729/35174824-9cd3b262-fd25-11e7-9fa0-2fe951518814.png)

![image](https://user-images.githubusercontent.com/3800729/35174806-8deaa0d0-fd25-11e7-9c2a-3a043805fabd.png)

The standard for iOS-style toggles is slide right to get it on/enable/green and left to get it off/disable/red.
![image](https://user-images.githubusercontent.com/3800729/35173998-8a4f2e6c-fd22-11e7-9edb-b9ee86236a54.png)
 

Version found:
GRG January 2018

**Comment by topowright** [comment]
@lfunkhouser do you know if we heard back from core on this issue?

**Comment by adgiles** [comment]
Addressed in PR https://github.com/Esri/solutions-grg-widget/pull/155. 

No documentation change required. Just needs to be verified and moved up to devtopia
