### ISSUE TITLE
Show Halo toggle option in Label Settings is reversed

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-grg-widget#146]
Issue reported by @MikeTschudi 

### Bug or Enhancement
The Show Halo toggle options are reversed in the Label Settings 

### Repo Steps or Enhancement details
1. Open GRG widget
2. Select Define a Grid from an Area
3. Select By Dimension
4. Click the Settings button
5. Expand Label Settings
Note the Halo toggle button. The user slides the toggle right (red) to disable the option to show a halo and slides it left (green) to enable the option to show halo. 

### Screenshots
![image](https://user-images.githubusercontent.com/3800729/35175310-e64e4734-fd27-11e7-8c81-224b3ef60166.png)
![image](https://user-images.githubusercontent.com/3800729/35175312-e9c11edc-fd27-11e7-984e-f6a860bba93b.png)

The standard for iOS-style toggles is slide right to get it on/enable/green and left to get it off/disable/red.
![image](https://user-images.githubusercontent.com/3800729/35173998-8a4f2e6c-fd22-11e7-9edb-b9ee86236a54.png)
 
This is an issue in the Label Settings for:
- [x] Define a Grid from an Area > By Dimension
- [x] Define a Grid from an Area > By Reference System
- [x] Define a Grid from a Point > By Dimension
- [x] Define a Grid from a Point > By Reference System
- [x] Define a Grid from a Point > By Time and Speed

Version found:
GRG January 2018

**Comment by adgiles** [comment]
Addressed in PR https://github.com/Esri/solutions-grg-widget/pull/155. 

No documentation change required. Just needs to be verified and moved up to devtopia
