### ISSUE TITLE
GRG from Point using Time and Speed: Define number of rows and columns toggle options are reversed

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-grg-widget#147]
Issue reported by @MikeTschudi 

### Bug or Enhancement
The Define number of rows and columns toggle positions for "on" and "off" are reversed in the UI.

### Repo Steps or Enhancement details
1. Open GRG widget
2. Select Define a Grid from a Point
3. Select By Time and Speed
4. Note the Define number of rows and columns toggle button.

The user slides the toggle right (red) to disable the option to input specified number of horizontal and vertical cells and slides it left (green) to enable the option to input a specified number of horizontal and vertical cells. 

### Screenshots
![image](https://user-images.githubusercontent.com/3800729/35177723-8ae75c28-fd36-11e7-91a4-4a8508b1a7ae.png)
![image](https://user-images.githubusercontent.com/3800729/35177727-92b41108-fd36-11e7-88c7-e2ce4189c03a.png)

The standard for iOS-style toggles is slide right to get it on/enable/green and left to get it off/disable/red.
![image](https://user-images.githubusercontent.com/3800729/35173998-8a4f2e6c-fd22-11e7-9edb-b9ee86236a54.png)
 

Version found:
GRG January 2018
WAB (Dev Edition) 2.7

**Comment by adgiles** [comment]
Addressed in PR https://github.com/Esri/solutions-grg-widget/pull/155. 

No documentation change required. Just needs to be verified and moved up to devtopia
