### ISSUE TITLE
When widget configuration is locked, provide warning

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-grg-widget#151]
### Bug or Enhancement
When widget settings are locked in the configuration. The settings button is still displayed on the widget but does not do anything. When the user clicks the settings button on a widget that has the configuration locked, a message should display to the user explaining that the settings have been locked on the widget before it was deployed.

**Comment by adgiles** [comment]
See discussion in this issue https://github.com/Esri/solutions-grg-widget/issues/80

**Comment by dfoll** [comment]
@adgiles I have reviewed and am familiar with the discussion in #80 . I could go with either method .... a.) visually displaying that the settings are locked or b.) just not having the settings button available at all .... personally i like option b.) of not displaying it at all, so maybe we should make that decision when we pull the issue into a sprint.

**Comment by adgiles** [comment]
Duplicate issue as #80 can be closed
