### ISSUE TITLE
Define Grid from a Point by Dimension preview point does not disappear

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-grg-widget#152]
### Bug or Enhancement
As stated in the checklist test, when creating a grid from a point by dimension, the preview point should disappear.

### Repo Steps or Enhancement details
1. Paste 17TNG6990462659 into the GRG origin box (Presque Isle state park) input should also read that you gave it an MGRS coordinate.
2. Change the number of horizontal and vertical cells if you wish
3. Change the Cell Width and Height if you wish
4. Click Create GRG

Preview point is still shown.

### Screenshots

![image](https://user-images.githubusercontent.com/5322669/35410448-53f58c38-01ca-11e8-8550-84cc4ef25b8d.png)
(preview point is still displayed after grid creation)

In my opinion, I like the preview/origin point still displaying. My recommendation is to update the checklist test to remove this step

**Comment by topowright** [comment]
The checklist needs to be updated based on the functionality.

**Comment by adgiles** [comment]
Checklist updated.

Step removed that stated the GRG origin point will disappear when creating a GRG from Point by Dimension
