### ISSUE TITLE
Address comments from GRG initial code review

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-grg-widget#153]
There was a pull request opened in devtopia for the initial commit of the GRG code. The Beijing team has reviewed https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11651 and have some additional comments/changes to be made. Junshan does his review by making each thing he wants addressed as a separate comment on the PR, so I will list them the same way here

**Comment by kgonzago** [comment]
@dfoll Assisted with moving comments from Junshan's code review
- [ ] remove console log
- [ ] replace single with double quotes in nls strings.js
- [ ] check measurements units in jimu to reduce translation
- [ ] double check any non-localized strings
- [ ] Refactor widget and setting pages to refence common files

**Comment by adgiles** [comment]
Issues above have been addressed in this PR https://github.com/Esri/solutions-grg-widget/pull/154

I cannot use the measurement labels from the jimu due to how the dropdowns are being initialized in the _loadOptionsForDropDown function within GridSettings.js. This function requires the appropriate labels to be present within the gridSettings object in the widget's nls/strings.js

**Comment by dfoll** [comment]
from junshan
is this a temp file?
![image](https://user-images.githubusercontent.com/5322669/35578857-11f01adc-059a-11e8-974b-dc8c2b264e50.png)

**Comment by dfoll** [comment]
from junshan
all strings should be in double quotation marks.
![image](https://user-images.githubusercontent.com/5322669/35578903-2fd4c2dc-059a-11e8-8732-4ed3cd48284c.png)

**Comment by dfoll** [comment]
from junshan
some strings (like units) are in jimu, can you use them to reduce translation?
![image](https://user-images.githubusercontent.com/5322669/35578956-547ac9d8-059a-11e8-849b-d16d96054879.png)

**Comment by dfoll** [comment]
from junshan 
please clean this line
![image](https://user-images.githubusercontent.com/5322669/35578991-6b24f41a-059a-11e8-8a4b-61a8cbe93dc1.png)

**Comment by dfoll** [comment]
from junshan
please clean this log and other debugging logs
![image](https://user-images.githubusercontent.com/5322669/35579023-84ddf8ca-059a-11e8-8e88-63ce97eeb2b4.png)

**Comment by lfunkhouser** [comment]
@dfoll has this been merged and is it ready to be verified?

**Comment by dfoll** [comment]
these changes have been added as commits in devtopia. I requested another code review from Junshan. This can be closed. If something else comes out of Junshan's next code review we can open a new issue for that.

**Comment by dfoll** [comment]
removing checklist tag because none of these changes affect the way a user/tester interacts with the widget.
