### ISSUE TITLE
Release-ready GRG 

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-grg-widget#178]
We need to fold in UI changes from the WAB team.

Files:
- [GRG.zip](https://github.com/Esri/solutions-grg-widget/files/1767693/GRG.zip)
- [icons.zip](https://github.com/Esri/solutions-grg-widget/files/1767697/icons.1.zip)

 Actions needed:
- [x] Review changes/suggestions from WAB team
- [x] Implement UI changes
- [x] Code Review
- [x] Push to Devtopia
- [x] Test on Developer Edition daily
- [x] Test on DevEXT

FYI @topowright @ACueva @dfoll

**Comment by adgiles** [comment]
Changes made per UI feedback, worked with @kgonzago to update devtopia. Changes in this PR https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11987

**Comment by dfoll** [comment]
Tested on Dev Edition daily snapshot. 
Only change I noticed is that there are now tabs when you access settings from within a deployed widget, where previously there were options you expanded, so I updated the doc accordingly.
