### ISSUE TITLE
Lock settings should change the gear settings icon style

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-grg-widget#80]
### Widget
GRG

### Bug or Enhancement
Right now, when you enable lock settings on the configuration page, the only indication that the settings have been disabled is a tooltip if you hover over the gear. If you click, however, nothing happens. I imagine that there may no longer be a click event on the settings gear if it has been disabled, but I'm wondering if it would be possible to change the color of the gear to red or an obviously lighter gray if the lock settings are on. I think if that is possible it would reduce confusion regarding lock settings: 

The gear is the same regardless of whether lock settings are enabled or not:
![image](https://user-images.githubusercontent.com/13024357/30458848-3fb7b0aa-9962-11e7-9711-5d9836008cc7.png)

**Comment by dfoll** [comment]
I could go with either method .... a.) visually displaying that the settings are locked or b.) just not having the settings button available at all .... personally i like option b.) of not displaying it at all, so maybe we should make that decision when we pull the issue into a sprint.

**Comment by adgiles** [comment]
Addressed as part of the UI review, when locked the icon now looks like the following:

**Light Theme**
![capture](https://user-images.githubusercontent.com/3740334/36848593-9c54d4fc-1d59-11e8-9804-7db697bf90ed.PNG)
**DarkTheme**
![capture1](https://user-images.githubusercontent.com/3740334/36848595-9def538c-1d59-11e8-978a-99231d0227f5.PNG)

Hovering over also provides the following messge

![untitled](https://user-images.githubusercontent.com/3740334/36848668-d78d4f0e-1d59-11e8-9e5b-f7cb40f7b3bd.png)

**Comment by dfoll** [comment]
Fix is good in the daily snapshot
